version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app # For development, sync local changes
      - /app/node_modules # Don't overwrite node_modules in container
      - /app/.next # Persist .next folder if needed for dev
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=development
    # depends_on:
    #   - backend # Enable if frontend needs backend during its build/startup

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # For development, sync local changes
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    # The command to run the FastAPI app will be in the backend Dockerfile.
    # For Celery workers, we might override the command or have a separate service definition.

  redis:
    image: redis:alpine
    ports:
      - "6379:6379" # Expose Redis to host for debugging if needed
    volumes:
      - redis_data:/data # Optional: for Redis data persistence

volumes:
  redis_data:
    driver: local