services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
        NEXT_PUBLIC_ASSET_PREFIX: ${NEXT_PUBLIC_ASSET_PREFIX}
    volumes:
      - /app/.next # Persists the .next build cache, can speed up server restarts.
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=development 
    # ports: # As per your original, not exposing directly
    #   - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-research"
      - "traefik.http.routers.research.entrypoints=http"
      - "traefik.http.routers.research.rule=Host(`research.no13productions.com`)"
      - "traefik.http.routers.research.middlewares=traefik-https-redirect"
      - "traefik.http.routers.research-secure.entrypoints=https"
      - "traefik.http.routers.research-secure.rule=Host(`research.no13productions.com`)"
      - "traefik.http.routers.research-secure.middlewares=secure-headers,rate-limit,ssl-forwarder"
      - "traefik.http.middlewares.ssl-forwarder.headers.customRequestHeaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.research-secure.tls=true"
      - "traefik.http.routers.research-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.research-secure.tls.options=default"
      - "traefik.http.services.research-secure.loadbalancer.server.port=3000"
    depends_on:
      - backend
    networks:
      - traefik-research
      - researcher

  # ... your other services (backend, backend_worker, redis) remain the same
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app # For development, sync local changes
    env_file:
      - ./backend/.env
    environment:
      - REDIS_PASSWORD=debugpassword # Matching the redis service for debugging
      - FRONTEND_URL=http://frontend:3000 # Adjusted to match the frontend service
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID} # Please replace with your actual Google Project ID
    networks:
      - researcher
    depends_on:
      - redis

  backend_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - REDIS_URL=redis://:debugpassword@redis:6379/0 # Hardcoded for debugging
      - CELERY_RESULTS_BACKEND_URL=redis://:debugpassword@redis:6379/0 # Hardcoded for debugging
      - FRONTEND_URL=https://research.no13productions.com
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID} # Please replace with your actual Google Project ID
    networks:
      - researcher
    depends_on:
      - redis
    command: celery -A celery_app worker --loglevel=info

  redis:
    image: redis:alpine
    networks:
      - researcher
    volumes:
      - redis_data:/data # Optional: for Redis data persistence
    environment:
      - REDIS_PASSWORD=debugpassword # Use an environment variable for password
    command: redis-server --requirepass debugpassword # Set password
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "debugpassword", "--raw", "incr", "ping"] # Basic health check
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  redis_data:
    driver: local

networks:
  traefik-research:
    external: true
  researcher:
    driver: bridge
